### PR TITLE
Update version 24.0 to 24.0.1

### PR DESCRIPTION
**Pull request by aphex3k**
Should one update the folder for 24.0 or create a new folder for 24.0.1? I went with the first option for now.

### CODE REVIEW

**Comment by Goro2030** [comment]
What's new/bug fix in 24.0.1?

**Comment by Goro2030** [comment]
https://github.com/bitcoin/bitcoin/pull/26616

**Comment by aphex3k** [comment]
> [bitcoin/bitcoin#26616](https://github.com/bitcoin/bitcoin/pull/26616)

Did you answer your own question? :)

**Comment by Goro2030** [comment]
> > [bitcoin/bitcoin#26616](https://github.com/bitcoin/bitcoin/pull/26616)
> 
> Did you answer your own question?

Of course. Recursive questioning :)

**Review by AaronDewes — APPROVED** [review]
> Should one update the folder for 24.0 or create a new folder for 24.0.1? I went with the first option for now.

Previously, new folders were only created for major releases. Minor releases kept the folder of the previous release. So what you did seems correct.

**Comment by aphex3k** [comment]
👀

**Comment by nolim1t** [comment]
Sorry about that I'm on the road with sporadic internet. I'll look at it in the next few days, unless @lukechilds  or @AaronDewes wants to help. I think they also have commit access to this project too

**Comment by AaronDewes** [comment]
I don't have any access to this repo (Only the Specter repo), but @lukechilds probably does have access here.

**Comment by aphex3k** [comment]
I'll guess everybody is in holiday mode and we gotta wait patiently :P

**Comment by nolim1t** [comment]
Merged in master but will tag it in the next few days (which will trigger the automated build) if no one  has already done it

**Comment by lukechilds** [comment]
I'm not very familiar with the release process on this repo but looking through the past releases it looks like we just do a manual tag of `<version>-build-<n>` and then GitHub Actions takes over for those commit patterns so I've tagged: [v24.0.1+build37](https://github.com/lncm/docker-bitcoind/releases/tag/v24.0.1%2Bbuild37)

**Comment by nolim1t** [comment]
There's a script for that in scripts.. thanks for trying. I'll take a look tommorrow. Been a crazy week

**Comment by nolim1t** [comment]
Release script depends on two things

- your git "origin" is this project
- you have direct write access to the repo (now @AaronDewes has it too)

```bash

% ./scripts/new-release.sh v24.0.1
Creating tag: v24.0.1+build39…	done
Pushing tag: v24.0.1+build39…	Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 792 bytes | 792.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/lncm/docker-bitcoind.git
 * [new tag]         v24.0.1+build39 -> v24.0.1+build39
All done

```

**Comment by nolim1t** [comment]
All updated

**Pull request merged**
