### PR TITLE
0.21.1

### PR DESCRIPTION
**Pull request by AaronDewes**
@nolim1t Can you release 0.21.1?

@lukechilds We should include this in Umbrel 0.3.11, I don't think we can test this well enough to be ready on Monday.

### CODE REVIEW

**Comment by AaronDewes** [comment]
Seems like the release is only tagged, but not fully ready yet.

**Comment by nolim1t** [comment]
Seems the 0.21 build failed.  Ill look at the logs

**Comment by nolim1t** [comment]
Seems its not released yet

https://bitcoin.org/bin/

**Comment by AaronDewes** [comment]
That's what I wanted to say here:

> Seems like the release is only tagged, but not fully ready yet.

**Comment by AaronDewes** [comment]
It's on bitcoincore.org now, we'll have to wait for bitcoin.org only now.

**Comment by nolim1t** [comment]
I wonder if I should just build it from bitcoincore.org and see if it works.. so we can test for taproot

**Comment by nolim1t** [comment]
I am testing bitcoincore.org out from #55

**Comment by nolim1t** [comment]
0.21.1 is ready for testing and use, however the issue why it's failing is because it's not available from bitcoin.org ..

Once it's available for use I'll most probably merge this issue in.

Thanks for your contribution.

**Comment by nolim1t** [comment]
Rerunning the tests as its now on bitcoin.org

https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3667

**Comment by nolim1t** [comment]
Thanks for the PR .. As we everything is now on bitcoin.org and bitcoincore.org and working we can now merge this

**Pull request merged**
