### PR TITLE
25.0: re-enable GPG verification 

### PR DESCRIPTION
**Pull request by fanquake**
Update the keys list to use the new Guix sigs key location:
https://github.com/bitcoin-core/guix.sigs/tree/main/builder-keys

Import the keys currently listed there.

Re-enable source download and verification, using github.com rather than
bitcoin.org, as it doesn't have the latest available sources.

### CODE REVIEW

**Comment by nolim1t** [comment]
need to make sure #77 is in there first and make sure everything will get to the build part

**Comment by nolim1t** [comment]
Can we see if it builds with 25.0 added to https://github.com/fanquake/lncm-docker-bitcoind/blob/021b7cc710ff6fed0c36dc294a376fde88c6cc24/.github/workflows/test.yml#L29 ?

**Comment by fanquake** [comment]
> Can we see if it builds with 25.0 added to

Sure. I've cherry-picked your test commit into this PR.

**Comment by nolim1t** [comment]
All good merging. Thanks for the PR

**Pull request merged**
