### PR TITLE
Testing for v0.21.0 Release candidate & Final

### PR DESCRIPTION
**Pull request by nolim1t**
Testing for v0.21.0 Release candidate

### CODE REVIEW

**Comment by nolim1t** [comment]
image

Seems to be working

**Review by AaronDewes — APPROVED** [review]
Now that a final v0.21.0 has been tagged, it'd be great to have a release soon. Is there still an issue with this code or has it just not been tested enough yet?

**Comment by nolim1t** [comment]
> Now that a final v0.21.0 has been tagged, it'd be great to have a release soon. Is there still an issue with this code or has it just not been tested enough yet?

I've been running the release candidates fine..

Thanks for the review @AaronDewes

**Comment by nolim1t** [comment]
I've switched it back to the official release and will merge if everything looks good

**Comment by nolim1t** [comment]
[tagged](https://github.com/lncm/docker-bitcoind/releases/tag/v0.21.0%2Bbuild17) and [being built](https://github.com/lncm/docker-bitcoind/actions) as we speak

**Comment by nolim1t** [comment]
Built - [in testing now](https://hub.docker.com/layers/lncm/bitcoind/v0.21.0/images/sha256-5063933724c4c259b70c91fd1959994e09146b9dfb0e053976413589e05570cd?context=repo)

Just some issues with the release scripts right now (DNS it seems)

**Comment by nolim1t** [comment]
I've also sent a [Pull Request](https://github.com/getumbrel/umbrel/pull/423) to umbrel

**Comment by nolim1t** [comment]
Documentation pertaining to `v0.21.0` is all updated too. I've also addressed #46 regarding config stuff too.

 Merging this in, and will address any other issues with blocking failed building (so far there is an issue uploading release assets due to some DNS error, which has nothing to do with the docker releases.

I would also like to add in another alternate docker hub too (GHCR and maybe gitlab too) in future so we are more resilient to decentralization

**Pull request merged**
