### PR TITLE
add v24.0 of bitcoind

### PR DESCRIPTION
**Pull request by aphex3k**
Lets get the newly released v24 going :)

### CODE REVIEW

**Comment by nolim1t** [comment]
Thanks for the pull request

**Comment by nolim1t** [comment]
I'll take a look at it and add it in

**Comment by nolim1t** [comment]
Anyone else having trouble building 24.0 ?

```
docker build --tag nolim1t/bitcoind:24.0 --build-arg "ARCH=arm64v8" .
```

yields an error locally

```
#36 38.39   CXX      wallet/libbitcoin_wallet_a-scriptpubkeyman.o
#36 40.46   CXX      wallet/libbitcoin_wallet_a-spend.o
#36 40.69   CXX      wallet/libbitcoin_wallet_a-transaction.o
#36 42.60   CXX      wallet/libbitcoin_wallet_a-wallet.o
#36 44.81   CXX      wallet/libbitcoin_wallet_a-walletdb.o
#36 343.4 g++: fatal error: Killed signal terminated program cc1plus
#36 343.4 compilation terminated.
#36 343.4 make[2]: *** [Makefile:11293: wallet/libbitcoin_wallet_a-scriptpubkeyman.o] Error 1
#36 343.4 make[2]: *** Waiting for unfinished jobs....
#36 472.4 g++: fatal error: Killed signal terminated program cc1plus
#36 472.4 compilation terminated.
#36 472.4 make[2]: *** [Makefile:11335: wallet/libbitcoin_wallet_a-wallet.o] Error 1

```

I can also see it failing from the build script too

**Comment by nolim1t** [comment]
ending up with different results on the github action builder. Will see if the last commit https://github.com/lncm/docker-bitcoind/pull/68/commits/53526e261c3a95eba0ec610f79bdcc74b009ba58 fixes this

**Comment by nolim1t** [comment]
Looks like this is building so will be the 24.0 branch (sans tests)

**Comment by Goro2030** [comment]
Thanks for doing this as always @nolim1t !! Is the build passing already?

**Comment by nolim1t** [comment]
Merged and now building

**Comment by nolim1t** [comment]
Built 

https://github.com/lncm/docker-bitcoind/releases/tag/v24.0%2Bbuild36

**Comment by Goro2030** [comment]
Thanks!! Bitcoin has NoLimit! 😁

**Pull request merged**
